# Generated by Django 4.2 on 2025-10-31 22:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('PARTIDO', 'Partido'), ('TORNEO', 'Torneo')], db_index=True, max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='app.categoria')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='app.entrenador')),
            ],
            options={
                'ordering': ['categoria__slug', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrador'), ('EQUIP', 'Equipo Administrativo'), ('ENTRE', 'Entrenador'), ('JUGAD', 'Jugador'), ('SOCIO', 'Socio')], db_index=True, default='SOCIO', max_length=5)),
                ('run', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='RUN inválido. Ejemplo: 12.345.678-5', regex='^\\d{1,2}\\.?\\d{3}\\.?\\d{3}-[\\dkK]$')], verbose_name='RUN/DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Teléfono inválido. Usa sólo dígitos y opcional '+'.", regex='^\\+?\\d{7,15}$')])),
                ('primer_nombre', models.CharField(max_length=40)),
                ('segundo_nombre', models.CharField(blank=True, max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo': 'SOCIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='socio', to='app.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='app.equipo')),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo': 'JUGAD'}, on_delete=django.db.models.deletion.PROTECT, related_name='jugador', to='app.perfil')),
            ],
            options={
                'ordering': ['equipo__categoria__slug', 'equipo__nombre', 'perfil__apellido_paterno', 'perfil__apellido_materno'],
            },
        ),
        migrations.CreateModel(
            name='EquipoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
                ('perfil', models.OneToOneField(limit_choices_to={'tipo': 'EQUIP'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_administrativo', to='app.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actividaddeportiva')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='perfil',
            field=models.OneToOneField(limit_choices_to={'tipo': 'ENTRE'}, on_delete=django.db.models.deletion.PROTECT, related_name='entrenador', to='app.perfil'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente')], db_index=True, default='P', max_length=1)),
                ('fecha_hora_marcaje', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='app.actividaddeportiva')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to='app.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='app.jugador')),
            ],
            options={
                'ordering': ['-fecha_hora_marcaje'],
            },
        ),
        migrations.AddField(
            model_name='actividaddeportiva',
            name='equipos',
            field=models.ManyToManyField(related_name='actividades', through='app.EquipoActividad', to='app.equipo'),
        ),
        migrations.AddIndex(
            model_name='jugador',
            index=models.Index(fields=['equipo'], name='app_jugador_equipo__c078da_idx'),
        ),
        migrations.AddIndex(
            model_name='jugador',
            index=models.Index(fields=['activo'], name='app_jugador_activo_4bc2a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipoactividad',
            unique_together={('actividad', 'equipo')},
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombre', 'categoria'), name='uq_equipo_nombre_categoria'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['actividad'], name='app_asisten_activid_2edcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['entrenador'], name='app_asisten_entrena_7b5092_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha_hora_marcaje'], name='app_asisten_fecha_h_f91c20_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('jugador', 'actividad'), name='uq_asistencia_jugador_actividad'),
        ),
        migrations.AddConstraint(
            model_name='actividaddeportiva',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='ck_actividad_rango_fechas'),
        ),
    ]
