# Generated by Django 4.2 on 2025-11-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddeportiva',
            name='entrenador_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'ENTRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsable', to='app.perfil'),
        ),
        migrations.AddField(
            model_name='actividaddeportiva',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividaddeportiva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
