# Generated by Django 4.2 on 2025-11-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividaddeportiva',
            name='lugar',
        ),
    ]
