# Generated by Django 4.2 on 2025-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='entrenador',
            field=models.ForeignKey(limit_choices_to={'tipo': 'ENTRE'}, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to='app.perfil'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='entrenador',
            field=models.ForeignKey(limit_choices_to={'tipo': 'ENTRE'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_dirigidos', to='app.perfil'),
        ),
        migrations.DeleteModel(
            name='Entrenador',
        ),
    ]
