# Generated by Django 4.2 on 2025-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_actividaddeportiva_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddeportiva',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
    ]
