# Generated by Django 4.2 on 2025-11-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actividaddeportiva_entrenador_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividaddeportiva',
            name='entrenador_responsable',
        ),
        migrations.RemoveField(
            model_name='actividaddeportiva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='actividaddeportiva',
            name='hora_inicio',
        ),
    ]
