# Generated by Django 4.2 on 2025-10-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=6)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncuentroDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('num_celular', models.PositiveIntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.entrenador')),
            ],
            options={
                'unique_together': {('id', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('num_celular', models.PositiveIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('num_celular', models.PositiveIntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('colegio', models.CharField(blank=True, max_length=60, null=True)),
                ('curso', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.equipo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.socio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('num_celular', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_marcaje', models.DateTimeField()),
                ('anotaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('actividad_deportiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.encuentrodeportivo')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entrenador')),
                ('evento_deportivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entrenamiento')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jugador')),
                ('marcaje_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
            ],
            options={
                'unique_together': {('permiso', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='EquipoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo')),
                ('evento_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entrenamiento')),
            ],
            options={
                'unique_together': {('equipo', 'evento_deportivo')},
            },
        ),
        migrations.CreateModel(
            name='EquipoEncuentroDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_deportiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.encuentrodeportivo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipo')),
            ],
            options={
                'unique_together': {('actividad_deportiva', 'equipo')},
            },
        ),
    ]
