# Generated by Django 4.2 on 2025-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_actividaddeportiva_entrenador_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddeportiva',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
