# Generated by Django 4.2 on 2025-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_actividaddeportiva_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddeportiva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
    ]
