# Generated by Django 4.2 on 2025-10-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_actividaddeportiva_cargo_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadDeportiva',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('sub_14', 'Sub 14'), ('sub_16', 'Sub 16'), ('sub_18', 'Sub 18')], max_length=6),
        ),
        migrations.AlterField(
            model_name='encuentrodeportivo',
            name='tipo',
            field=models.CharField(choices=[('Entrenamiento', 'Entrenamiento'), ('Práctica', 'Práctica'), ('Acondicionamiento', 'Acondicionamiento'), ('Taller', 'Taller'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='curso',
            field=models.CharField(blank=True, choices=[('octavo_basico', 'Octavo Básico'), ('primero_medio', 'Primero Medio'), ('segundo_medio', 'Segundo Medio'), ('tercero_medio', 'Tercero Medio'), ('cuarto_medio', 'Cuarto Medio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
