# Generated by Django 4.2 on 2025-10-17 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.socio'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.usuario'),
        ),
    ]
